name: "reema al-zaben"
description: "[My thoughts, organized.]"
author: "Reema Al-Zaben"

# url: "http://localhost:4000"
url: "http://ralzaben.github.io"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
